name: Create Twitter Thread

on:
  schedule:
    - cron: '0 10 * * *' # 10 AM UTC
  workflow_dispatch:

jobs:
  create_twitter_thread:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1

      - name: Install Dependencies
        run: npm install

      - name: Run Job
        run: node src/actions/create_twitter_thread.js
