name: Create Twitter Thread

on:
  schedule:
    - cron: '30 09 * * *' # 9:30 AM UTC
  workflow_dispatch:

jobs:
  create_twitter_thread:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3.4.1

      - name: Install Dependencies
        run: npm install

      - name: Run Job
        run: node src/actions/create_twitter_thread.mjs
        env:
          NEXT_PUBLIC_SUPABASE_ANON_KEY: ${{ secrets.NEXT_PUBLIC_SUPABASE_ANON_KEY }}
          NEXT_PUBLIC_SUPABASE_URL: ${{ secrets.NEXT_PUBLIC_SUPABASE_URL }}
          OPEN_AI_API_KEY: ${{ secrets.OPEN_AI_API_KEY }}
          OPEN_AI_ORGANIZATION: ${{ secrets.OPEN_AI_ORGANIZATION }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
